class Autogenerated {
  List<SaleTotal> saleTotal;
  List<PurchaseTotal> purchaseTotal;
  List<ExpenseTotal> expenseTotal;
  List<PayableTotal> payableTotal;
  List<ReceiveableTotal> receiveableTotal;

  Autogenerated(
      {this.saleTotal,
      this.purchaseTotal,
      this.expenseTotal,
      this.payableTotal,
      this.receiveableTotal});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    if (json['saleTotal'] != null) {
      saleTotal = new List<SaleTotal>();
      json['saleTotal'].forEach((v) {
        saleTotal.add(new SaleTotal.fromJson(v));
      });
    }
    if (json['purchaseTotal'] != null) {
      purchaseTotal = new List<PurchaseTotal>();
      json['purchaseTotal'].forEach((v) {
        purchaseTotal.add(new PurchaseTotal.fromJson(v));
      });
    }
    if (json['expenseTotal'] != null) {
      expenseTotal = new List<ExpenseTotal>();
      json['expenseTotal'].forEach((v) {
        expenseTotal.add(new ExpenseTotal.fromJson(v));
      });
    }
    if (json['payableTotal'] != null) {
      payableTotal = new List<PayableTotal>();
      json['payableTotal'].forEach((v) {
        payableTotal.add(new PayableTotal.fromJson(v));
      });
    }
    if (json['receiveableTotal'] != null) {
      receiveableTotal = new List<ReceiveableTotal>();
      json['receiveableTotal'].forEach((v) {
        receiveableTotal.add(new ReceiveableTotal.fromJson(v));
      });
    }
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    if (this.saleTotal != null) {
      data['saleTotal'] = this.saleTotal.map((v) => v.toJson()).toList();
    }
    if (this.purchaseTotal != null) {
      data['purchaseTotal'] =
          this.purchaseTotal.map((v) => v.toJson()).toList();
    }
    if (this.expenseTotal != null) {
      data['expenseTotal'] = this.expenseTotal.map((v) => v.toJson()).toList();
    }
    if (this.payableTotal != null) {
      data['payableTotal'] = this.payableTotal.map((v) => v.toJson()).toList();
    }
    if (this.receiveableTotal != null) {
      data['receiveableTotal'] =
          this.receiveableTotal.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class SaleTotal {
  String saleTotal;

  SaleTotal({this.saleTotal});

  SaleTotal.fromJson(Map<String, dynamic> json) {
    saleTotal = json['sale_Total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['sale_Total'] = this.saleTotal;
    return data;
  }
}

class PurchaseTotal {
  String purchaseTotal;

  PurchaseTotal({this.purchaseTotal});

  PurchaseTotal.fromJson(Map<String, dynamic> json) {
    purchaseTotal = json['purchase_Total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['purchase_Total'] = this.purchaseTotal;
    return data;
  }
}

class ExpenseTotal {
  String expenseTotal;

  ExpenseTotal({this.expenseTotal});

  ExpenseTotal.fromJson(Map<String, dynamic> json) {
    expenseTotal = json['expense_Total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['expense_Total'] = this.expenseTotal;
    return data;
  }
}

class PayableTotal {
  String payableTotal;

  PayableTotal({this.payableTotal});

  PayableTotal.fromJson(Map<String, dynamic> json) {
    payableTotal = json['payable_Total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['payable_Total'] = this.payableTotal;
    return data;
  }
}

class ReceiveableTotal {
  String receiveableTotal;

  ReceiveableTotal({this.receiveableTotal});

  ReceiveableTotal.fromJson(Map<String, dynamic> json) {
    receiveableTotal = json['receiveable_Total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['receiveable_Total'] = this.receiveableTotal;
    return data;
  }
}
